/**
 * Mock catalog for M1 — stand-in for the external searcher (M2).
 *
 * Values mirror Telas Bayón's real catalog so test cases are meaningful:
 * fabric types (Percal, Popelina, Loneta, Blackout, Polar, Panama, Gobelino),
 * real colors (Arena, Chocolate, Blanco, Negro, Rojo, Turquesa, Olivo),
 * widths 110–320 cm, prices ~99–659 MXN incl. IVA.
 *
 * This is the ONLY file M2 should retire: the searcher will return objects of
 * the same `Producto` shape, so the rest of the pipeline is untouched.
 */

import type { Producto } from "@/lib/mcp/types";

const STOREFRONT = "https://telasbayon.com/products";
const IMG = "https://telasbayon.com/cdn/shop/products";

export const MOCK_CATALOGO: Producto[] = [
  {
    id: "BAY-PER-ARE-001",
    nombre: "Percal Liso Arena",
    coleccion: "Vestir",
    color: "Arena",
    tipo_de_tela: "Percal",
    estilo: "Liso",
    composicion: "100% Algodón",
    ancho_cm: 150,
    precio_mxn: 129,
    disponible: true,
    url: `${STOREFRONT}/percal-liso-arena`,
    imagen_url: `${IMG}/percal-liso-arena.jpg`,
    descripcion: "Percal de algodón ligero, ideal para confección de vestir.",
  },
  {
    id: "BAY-PER-BLA-002",
    nombre: "Percal Liso Blanco",
    coleccion: "Vestir",
    color: "Blanco",
    tipo_de_tela: "Percal",
    estilo: "Liso",
    composicion: "100% Algodón",
    ancho_cm: 150,
    precio_mxn: 119,
    disponible: true,
    url: `${STOREFRONT}/percal-liso-blanco`,
    imagen_url: `${IMG}/percal-liso-blanco.jpg`,
    descripcion: "Percal blanco clásico, suave y fresco.",
  },
  {
    id: "BAY-POP-RAY-003",
    nombre: "Popelina Rayas Turquesa",
    coleccion: "Vestir",
    color: "Turquesa",
    tipo_de_tela: "Popelina",
    estilo: "Rayas",
    composicion: "Algodón/Poliéster",
    ancho_cm: 145,
    precio_mxn: 159,
    disponible: true,
    url: `${STOREFRONT}/popelina-rayas-turquesa`,
    imagen_url: `${IMG}/popelina-rayas-turquesa.jpg`,
    descripcion: "Popelina con rayas, firme y de buena caída para camisería.",
  },
  {
    id: "BAY-POP-EST-004",
    nombre: "Popelina Estampado Floral Rojo",
    coleccion: "Vestir",
    color: "Rojo",
    tipo_de_tela: "Popelina",
    estilo: "Estampado",
    composicion: "100% Algodón",
    ancho_cm: 145,
    precio_mxn: 175,
    disponible: false,
    url: `${STOREFRONT}/popelina-estampado-floral-rojo`,
    imagen_url: `${IMG}/popelina-estampado-floral-rojo.jpg`,
    descripcion: "Popelina con estampado floral en tonos rojos.",
  },
  {
    id: "BAY-LON-CHO-005",
    nombre: "Loneta Lisa Chocolate",
    coleccion: "Tapicería",
    color: "Chocolate",
    tipo_de_tela: "Loneta",
    estilo: "Liso",
    composicion: "Algodón/Poliéster",
    ancho_cm: 280,
    precio_mxn: 289,
    disponible: true,
    url: `${STOREFRONT}/loneta-lisa-chocolate`,
    imagen_url: `${IMG}/loneta-lisa-chocolate.jpg`,
    descripcion: "Loneta resistente para tapizado y cojinería de alto uso.",
  },
  {
    id: "BAY-LON-OLI-006",
    nombre: "Loneta Lisa Olivo",
    coleccion: "Tapicería",
    color: "Olivo",
    tipo_de_tela: "Loneta",
    estilo: "Liso",
    composicion: "Algodón/Poliéster",
    ancho_cm: 280,
    precio_mxn: 299,
    disponible: true,
    url: `${STOREFRONT}/loneta-lisa-olivo`,
    imagen_url: `${IMG}/loneta-lisa-olivo.jpg`,
    descripcion: "Loneta verde olivo, robusta para tapicería y decoración.",
  },
  {
    id: "BAY-BLK-NEG-007",
    nombre: "Blackout Liso Negro",
    coleccion: "Cortinas",
    color: "Negro",
    tipo_de_tela: "Blackout",
    estilo: "Liso",
    composicion: "Poliéster",
    ancho_cm: 300,
    precio_mxn: 459,
    disponible: true,
    url: `${STOREFRONT}/blackout-liso-negro`,
    imagen_url: `${IMG}/blackout-liso-negro.jpg`,
    descripcion: "Blackout que bloquea la luz, ideal para recámaras.",
  },
  {
    id: "BAY-BLK-ARE-008",
    nombre: "Blackout Liso Arena",
    coleccion: "Cortinas",
    color: "Arena",
    tipo_de_tela: "Blackout",
    estilo: "Liso",
    composicion: "Poliéster",
    ancho_cm: 300,
    precio_mxn: 449,
    disponible: false,
    url: `${STOREFRONT}/blackout-liso-arena`,
    imagen_url: `${IMG}/blackout-liso-arena.jpg`,
    descripcion: "Blackout color arena, oscurecimiento total y aislante.",
  },
  {
    id: "BAY-POL-TUR-009",
    nombre: "Polar Liso Turquesa",
    coleccion: "Blancos",
    color: "Turquesa",
    tipo_de_tela: "Polar",
    estilo: "Liso",
    composicion: "Poliéster",
    ancho_cm: 160,
    precio_mxn: 99,
    disponible: true,
    url: `${STOREFRONT}/polar-liso-turquesa`,
    imagen_url: `${IMG}/polar-liso-turquesa.jpg`,
    descripcion: "Polar suave y abrigador para cobijas y batas.",
  },
  {
    id: "BAY-POL-ROJ-010",
    nombre: "Polar Estampado Rojo",
    coleccion: "Blancos",
    color: "Rojo",
    tipo_de_tela: "Polar",
    estilo: "Estampado",
    composicion: "Poliéster",
    ancho_cm: 160,
    precio_mxn: 115,
    disponible: true,
    url: `${STOREFRONT}/polar-estampado-rojo`,
    imagen_url: `${IMG}/polar-estampado-rojo.jpg`,
    descripcion: "Polar estampado, cálido y ligero.",
  },
  {
    id: "BAY-PAN-BLA-011",
    nombre: "Panamá Liso Blanco",
    coleccion: "Vestir",
    color: "Blanco",
    tipo_de_tela: "Panama",
    estilo: "Liso",
    composicion: "Algodón/Poliéster",
    ancho_cm: 150,
    precio_mxn: 189,
    disponible: true,
    url: `${STOREFRONT}/panama-liso-blanco`,
    imagen_url: `${IMG}/panama-liso-blanco.jpg`,
    descripcion: "Tela Panamá de tejido firme, para manteles y uniformes.",
  },
  {
    id: "BAY-PAN-NEG-012",
    nombre: "Panamá Liso Negro",
    coleccion: "Vestir",
    color: "Negro",
    tipo_de_tela: "Panama",
    estilo: "Liso",
    composicion: "Algodón/Poliéster",
    ancho_cm: 150,
    precio_mxn: 189,
    disponible: true,
    url: `${STOREFRONT}/panama-liso-negro`,
    imagen_url: `${IMG}/panama-liso-negro.jpg`,
    descripcion: "Panamá negra, versátil para confección y manteleria.",
  },
  {
    id: "BAY-GOB-CHO-013",
    nombre: "Gobelino Bordado Chocolate",
    coleccion: "Tapicería",
    color: "Chocolate",
    tipo_de_tela: "Gobelino",
    estilo: "Bordado",
    composicion: "Poliéster",
    ancho_cm: 280,
    precio_mxn: 599,
    disponible: true,
    url: `${STOREFRONT}/gobelino-bordado-chocolate`,
    imagen_url: `${IMG}/gobelino-bordado-chocolate.jpg`,
    descripcion: "Gobelino con motivos bordados, elegante para tapizado fino.",
  },
  {
    id: "BAY-GOB-OLI-014",
    nombre: "Gobelino Estampado Olivo",
    coleccion: "Tapicería",
    color: "Olivo",
    tipo_de_tela: "Gobelino",
    estilo: "Estampado",
    composicion: "Poliéster",
    ancho_cm: 300,
    precio_mxn: 659,
    disponible: false,
    url: `${STOREFRONT}/gobelino-estampado-olivo`,
    imagen_url: `${IMG}/gobelino-estampado-olivo.jpg`,
    descripcion: "Gobelino estampado en olivo, alta densidad de tejido.",
  },
  {
    id: "BAY-PER-NEG-015",
    nombre: "Percal Estampado Negro",
    coleccion: "Vestir",
    color: "Negro",
    tipo_de_tela: "Percal",
    estilo: "Estampado",
    composicion: "100% Algodón",
    ancho_cm: 110,
    precio_mxn: 139,
    disponible: true,
    url: `${STOREFRONT}/percal-estampado-negro`,
    imagen_url: `${IMG}/percal-estampado-negro.jpg`,
    descripcion: "Percal estampado sobre fondo negro, fresco y ligero.",
  },
  {
    id: "BAY-LON-ARE-016",
    nombre: "Loneta Rayas Arena",
    coleccion: "Tapicería",
    color: "Arena",
    tipo_de_tela: "Loneta",
    estilo: "Rayas",
    composicion: "Algodón/Poliéster",
    ancho_cm: 320,
    precio_mxn: 319,
    disponible: true,
    url: `${STOREFRONT}/loneta-rayas-arena`,
    imagen_url: `${IMG}/loneta-rayas-arena.jpg`,
    descripcion: "Loneta a rayas en tono arena, ancho extra para cortinas.",
  },
];
